;;;; CYCO plugins sj eastwest sd3 djembe
;;;;
;;;; ew-sd3-bigdrums
;;;;  |
;;;;  +-- djembe
;;;;        Variations: 'REMO-16 'REMO-10 'ROSE

(param djembe nil)

(let ((keymap-table (make-hash-table))
      (remarks-table (make-hash-table)))
  (setf (gethash 'remo-16 keymap-table)
	(symbolic-keynumber-map 
	 (list (list 'BASS-1         (ew-keynumber 'C1))
	       (list 'BASS-2         (ew-keynumber 'D1))
	       (list 'BASS-3         (ew-keynumber 'E1))
	       (list 'MUTE-LH        (ew-keynumber 'F1))
	       (list 'MUTE-RH        (ew-keynumber 'G1))
	       (list 'MUTE-SLAP-1    (ew-keynumber 'A1))
	       (list 'MUTE-SLAP-2    (ew-keynumber 'B1))
	       (list 'OPEN-1         (ew-keynumber 'C2))
	       (list 'OPEN-2         (ew-keynumber 'D2))
	       (list 'OPEN-3         (ew-keynumber 'E2))
	       (list 'OPEN-SLAP-1    (ew-keynumber 'F2))
	       (list 'OPEN-SLAP-2    (ew-keynumber 'G2))
	       (list 'OPEN-SLAP-3    (ew-keynumber 'A2))
	       (list 'RIM-1          (ew-keynumber 'B1))
	       (list 'RIM-2          (ew-keynumber 'C2))
	       (list 'BASS-FLAM      (ew-keynumber 'D2))
	       (list 'OPEN-FLAM      (ew-keynumber 'E2))
	       (list 'OPEN-SLAP-FLAM (ew-keynumber 'F2))
	       (list 'SCRAPE-1       (ew-keynumber 'G2))
	       (list 'SCRAPE-2       (ew-keynumber 'A2))
	       (list 'FINGER-ROLL-1  (ew-keynumber 'B2))
	       (list 'FINGER-ROLL-2  (ew-keynumber 'C3))
	       (list 'MACHINE-GUN    (ew-keynumber 'D3))
	       (list 'OCEAN          (ew-keynumber 'E3))
	       (list 'FX-SLIDE       (ew-keynumber 'F3)))))
  (setf (gethash 'remo-16 remarks-table) "SD3 Big Drums Djembe 16in Remo")
  (setf (gethash 'rose keymap-table)
	(symbolic-keynumber-map 
	 (list (list 'OPEN       (ew-keynumber 'C1))
	       (list 'DOUBLE     (ew-keynumber 'D1))
	       (list 'LOW-MUTE-1 (ew-keynumber 'E1))
	       (list 'LOW-MUTE-2 (ew-keynumber 'F1))
	       (list 'LOW-SLAP-1 (ew-keynumber 'G1))
	       (list 'LOW-SLAP-2 (ew-keynumber 'A1))
	       (list 'SLAP       (ew-keynumber 'B1))
	       (list 'SLAP-FLAM  (ew-keynumber 'C2))
	       (list 'ROLLS-1    (ew-keynumber 'D2))
	       (list 'ROLLS-2    (ew-keynumber 'E2))
	       (list 'ROLLS-3    (ew-keynumber 'F2))
	       (list 'ROLLS-4    (ew-keynumber 'G2))
	       (list 'ROLLS-5    (ew-keynumber 'A2))
	       (list 'PERF-01    (ew-keynumber 'B2))
	       (list 'PERF-02    (ew-keynumber 'C3))
	       (list 'PERF-03    (ew-keynumber 'D3))
	       (list 'PERF-04    (ew-keynumber 'E3))
	       (list 'PERF-05    (ew-keynumber 'F3))
	       (list 'PERF-06    (ew-keynumber 'G3))
	       (list 'PERF-07    (ew-keynumber 'A3))
	       (list 'PERF-08    (ew-keynumber 'B3))
	       (list 'PERF-09    (ew-keynumber 'C4))
	       (list 'PERF-10    (ew-keynumber 'D4))
	       (list 'PERF-11    (ew-keynumber 'E4))
	       (list 'PERF-12    (ew-keynumber 'F4))
	       (list 'PERF-13    (ew-keynumber 'G4))
	       (list 'PERF-14    (ew-keynumber 'A4))
	       (list 'PERF-15    (ew-keynumber 'B4))
	       (list 'PERF-16    (ew-keynumber 'C5))
	       (list 'PERF-17    (ew-keynumber 'D5))
	       (list 'PERF-18    (ew-keynumber 'E5))
	       (list 'PERF-19    (ew-keynumber 'F5))
	       (list 'PERF-20    (ew-keynumber 'G5))
	       (list 'PERF-21    (ew-keynumber 'A5))
	       (list 'PERF-22    (ew-keynumber 'B5))
	       (list 'PERF-23    (ew-keynumber 'C6))
	       (list 'PERF-24    (ew-keynumber 'D6))
	       (list 'PERF-25    (ew-keynumber 'E6))
	       (list 'PERF-26    (ew-keynumber 'F6))
	       (list 'PERF-27    (ew-keynumber 'G6)))))
  (setf (gethash 'rose remarks-table) "SD3 Big Drums Djembe Ghana Solid Rose Djembe")
  (setf (gethash 'remo-10 keymap-table)
	(symbolic-keynumber-map
	 (list (list 'BASS-HIT       (ew-keynumber 'C1))
	       (list 'BASS-REP       (ew-keynumber 'D1))
	       (list 'BASS-SLIDE     (ew-keynumber 'E1))
	       (list 'BASS-FLAM      (ew-keynumber 'F1))
	       (list 'OPEN-LH        (ew-keynumber 'G1))
	       (list 'OPEN-RH        (ew-keynumber 'A1))
	       (list 'OPEN-REP       (ew-keynumber 'B1))
	       (list 'RIM-LH         (ew-keynumber 'C2))
	       (list 'RIM-RH         (ew-keynumber 'D2))
	       (list 'SLAP           (ew-keynumber 'E2))
	       (list 'FLAM           (ew-keynumber 'F2))
	       (list 'CENTER-SLAP-LH (ew-keynumber 'G2))
	       (list 'CENTER-SLAP-RH (ew-keynumber 'A2))
	       (list 'CENTER-MUTE-LH (ew-keynumber 'B2))
	       (list 'CENTER-MUTE-RH (ew-keynumber 'C3))
	       (list 'FLAM-MUTE      (ew-keynumber 'D3))
	       (list 'MUTE-LH        (ew-keynumber 'E3))
	       (list 'MUTE-RH        (ew-keynumber 'F3))
	       (list 'FINGER-ROLL-1  (ew-keynumber 'G3))
	       (list 'FINGER-ROLL-2  (ew-keynumber 'A3))
	       (list 'FINGER-ROLL-3  (ew-keynumber 'B3))
	       (list 'NAIL-1         (ew-keynumber 'C4))
	       (list 'NAIL-2         (ew-keynumber 'D4))
	       (list 'NAIL-3         (ew-keynumber 'E4))
	       (list 'NAIL-4         (ew-keynumber 'F4))
	       (list 'NAIL-5         (ew-keynumber 'G4))
	       (list 'NAIL-6         (ew-keynumber 'A4))
	       (list 'NAIL-7         (ew-keynumber 'B4))
	       (list 'NAIL-8         (ew-keynumber 'C5))
	       (list 'SLIDE-1        (ew-keynumber 'D5))
	       (list 'SLIDE-2        (ew-keynumber 'E5))
	       (list 'SLIDE-3        (ew-keynumber 'F5))
	       (list 'SLIDE-4        (ew-keynumber 'G5))
	       (list 'SLIDE-5        (ew-keynumber 'A5))
	       (list 'SLIDE-6        (ew-keynumber 'B5))
	       (list 'SLIDE-7        (ew-keynumber 'C6)))))
  (setf (gethash 'remo-10 remarks-table) "SD3 Small Drums Remo 10in Djembe Fiberskin")
  (sd3-instrument djembe ew-sd3-bigdrums keymap-table remarks-table)
  (sd3-query ?djembe 'djembe remarks-table))
