;;;; CYCO plugins sj eastwest sd3 tubano.lisp
;;;;
;;;; ew-sd3-bigdrums
;;;; |
;;;; +-- tubano
;;;;       14-NSL     - Remo NSL 14in
;;;;       12-NSL     - Remo NSL Tubano 12in
;;;;       12-NUSKIN  - Remo 12in Tubano NuSkin
;;;;       12-LADOMBE - Remo NSL Tubano LaDombe 12in
;;;;

(param tubano nil)

(let ((keymap-table (make-hash-table))
      (remarks-table (make-hash-table)))
  (setf (gethash '14-NSL keymap-table)
	(symbolic-keynumber-map
	 (list (list 'CENTER-FIST (ew-keynumber 'C1))
	       (list 'BASS-LH     (ew-keynumber 'D1))
	       (list 'BASS-RH     (ew-keynumber 'E1))
	       (list 'BASE-FLAM   (ew-keynumber 'F1))
	       (list 'MALLET-OPEN (ew-keynumber 'G1))
	       (list 'SLAP-LH     (ew-keynumber 'A1))
	       (list 'OPEN-LH     (ew-keynumber 'B1))
	       (list 'OPEN-RH     (ew-keynumber 'C2))
	       (list 'SLAP-RH     (ew-keynumber 'D2))
	       (list 'RIM-LH      (ew-keynumber 'E2))
	       (list 'RIM-RH      (ew-keynumber 'F2))
	       (list 'SLAP-FLAM   (ew-keynumber 'G2))
	       (list 'OPEN-FLAM   (ew-keynumber 'A2))
	       (list 'PERF-01     (ew-keynumber 'C3))
	       (list 'PERF-02     (ew-keynumber 'D3))
	       (list 'PERF-03     (ew-keynumber 'E3))
	       (list 'PERF-04     (ew-keynumber 'F3))
	       (list 'PERF-05     (ew-keynumber 'G3))
	       (list 'PERF-06     (ew-keynumber 'A3))
	       (list 'PERF-07     (ew-keynumber 'B3))
	       (list 'PERF-08     (ew-keynumber 'C4))
	       (list 'PERF-09     (ew-keynumber 'D4))
	       (list 'PERF-10     (ew-keynumber 'E4))
	       (list 'PERF-11     (ew-keynumber 'F4))
	       (list 'PERF-12     (ew-keynumber 'G4))
	       (list 'PERF-13     (ew-keynumber 'A4))
	       (list 'PERF-14     (ew-keynumber 'B4))
	       (list 'PERF-15     (ew-keynumber 'C5))
	       (list 'PERF-16     (ew-keynumber 'D5))
	       (list 'PERF-17     (ew-keynumber 'E5))
	       (list 'PERF-18     (ew-keynumber 'F5))
	       (list 'PERF-19     (ew-keynumber 'G5))
	       (list 'PERF-20     (ew-keynumber 'A5))
	       (list 'PERF-21     (ew-keynumber 'B5))
	       (list 'PERF-22     (ew-keynumber 'C6))
	       (list 'PERF-23     (ew-keynumber 'D6))
	       (list 'PERF-24     (ew-keynumber 'E6)))))
  (setf (gethash '14-nsl remarks-table) "SD3 Big Drums Remo NSL 14")
  (setf (gethash '12-NSL keymap-table)
	(symbolic-keynumber-map
	 (list (list 'OFF-CENTER-RH (ew-keynumber 'D2))
	       (list 'REP       (ew-keynumber 'E2))
	       (list 'FLAM      (ew-keynumber 'F2))
	       (list 'SLAP-REP  (ew-keynumber 'G2))
	       (list 'SLAP-FLAM (ew-keynumber 'A2))
	       (list 'RIM-LH    (ew-keynumber 'B2))
	       (list 'RIM-RH    (ew-keynumber 'C3))
	       (list 'ROLLS-P   (ew-keynumber 'D3))
	       (list 'ROLLS-MP  (ew-keynumber 'E3))
	       (list 'ROLLS-MF  (ew-keynumber 'F3))
	       (list 'ROLLS-F   (ew-keynumber 'G3))
	       (list 'PERF-FX-1 (ew-keynumber 'C4))
	       (list 'PERF-FX-2 (ew-keynumber 'D4))
	       (list 'PERF-FX-3 (ew-keynumber 'E4))
	       (list 'PERF-FX-4 (ew-keynumber 'F4))
	       (list 'PERF-FX-5 (ew-keynumber 'G4))
	       (list 'PERF-FX-6 (ew-keynumber 'A4))
	       (list 'PERF-FX-7 (ew-keynumber 'B4))
	       (list 'PERF-FX-8 (ew-keynumber 'C5))
	       (list 'PERF-FX-9 (ew-keynumber 'D5))
	       (list 'PERF-01   (ew-keynumber 'E5))
	       (list 'PERF-02   (ew-keynumber 'F5))
	       (list 'PERF-03   (ew-keynumber 'G5))
	       (list 'PERF-04   (ew-keynumber 'A5))
	       (list 'PERF-05   (ew-keynumber 'B5))
	       (list 'PERF-06   (ew-keynumber 'C6))
	       (list 'PERF-07   (ew-keynumber 'D6))
	       (list 'PERF-08   (ew-keynumber 'E6))
	       (list 'PERF-09   (ew-keynumber 'F6))
	       (list 'PERF-10   (ew-keynumber 'G6))
	       (list 'PERF-11   (ew-keynumber 'A6))
	       (list 'PERF-12   (ew-keynumber 'B6))
	       (list 'PERF-13   (ew-keynumber 'C7))
	       (list 'PERF-14   (ew-keynumber 'D7))
	       (list 'PERF-15   (ew-keynumber 'E7))
	       (list 'PERF-16   (ew-keynumber 'F7))
	       (list 'PERF-17   (ew-keynumber 'G7))
	       (list 'PERF-18   (ew-keynumber 'A7))
	       (list 'PERF-19   (ew-keynumber 'B7))
	       (list 'PERF-20   (ew-keynumber 'C8)))))
  (setf (gethash '12-nsl remarks-table) "SD3 Big Drums Remo NSL Tubano 12")
  (setf (gethash '12-nuskin keymap-table)
	(symbolic-keynumber-map
	 (list (list 'BASS-REP      (ew-keynumber 'C1))
	       (list 'BASS-SLIDE    (ew-keynumber 'D1))
	       (list 'BASS-FLAM     (ew-keynumber 'E1))
	       (list 'OPEN-REP      (ew-keynumber 'A1))
	       (list 'RIM-LH        (ew-keynumber 'B1))
	       (list 'RIM-RH        (ew-keynumber 'C2))
	       (list 'OPEN-REP-SLAP (ew-keynumber 'D2))
	       (list 'OPEN          (ew-keynumber 'E2))
	       (list 'FLAM          (ew-keynumber 'F2))
	       (list 'SLAP-FLMA     (ew-keynumber 'B2))
	       (list 'SLAP-MUTE-LH  (ew-keynumber 'C3))
	       (list 'SLAP-MUTE-RH  (ew-keynumber 'D3))
	       (list 'OFFCENTER-LH  (ew-keynumber 'F1))
	       (list 'OFFCENTER-RH  (ew-keynumber 'G1))
	       (list 'OFFCENTER-SLAP-LH (ew-keynumber 'G2))
	       (list 'OFFCENTER-SLAP-RH (ew-keynumber 'A2))
	       (list 'OFFCENTER-MUTE-LH (ew-keynumber 'E3))
	       (list 'OFFCENTER-MUTE-RH (ew-keynumber 'F3))
	       (list 'MACHINE-GUN   (ew-keynumber 'G3))
	       (list 'RIMROLL-1     (ew-keynumber 'A3))
	       (list 'RIMROLL-2     (ew-keynumber 'B3))
	       (list 'RIMROLL-3     (ew-keynumber 'C4))
	       (list 'SCRAPES-1     (ew-keynumber 'D4))
	       (list 'SCRAPES-2     (ew-keynumber 'E4))
	       (list 'SCRAPES-3     (ew-keynumber 'F4))
	       (list 'SCRAPES-4     (ew-keynumber 'G4))
	       (list 'SCRAPES-5     (ew-keynumber 'A4))
	       (list 'SCRAPES-6     (ew-keynumber 'B4))
	       (list 'SCRAPES-7     (ew-keynumber 'C5)))))
  (setf (gethash '12-nuskin remarks-table) "SD3 Big Drums 12in Tubano NuSkin")

  (setf (gethash '12-ledombe keymap-table)
	(symbolic-keynumber-map
	 (list (list 'BASS-LH   (ew-keynumber 'C1))
	       (list 'BASS-RH   (ew-keynumber 'D1))
	       (list 'BASS-REP  (ew-keynumber 'E1))
	       (list 'OPEN-LH   (ew-keynumber 'F1))
	       (list 'OPEN-RH   (ew-keynumber 'G1))
	       (list 'OPEN-REPS (ew-keynumber 'A1))
	       (list 'MALLET-LH (ew-keynumber 'B1))
	       (list 'MALLET-RH (ew-keynumber 'C2))
	       (list 'PERF-01 (ew-keynumber 'F2))
	       (list 'PERF-02 (ew-keynumber 'G2))
	       (list 'PERF-03 (ew-keynumber 'A2))
	       (list 'PERF-04 (ew-keynumber 'B2))
	       (list 'PERF-05 (ew-keynumber 'C3))
	       (list 'PERF-06 (ew-keynumber 'D3))
	       (list 'PERF-07 (ew-keynumber 'E3))
	       (list 'PERF-08 (ew-keynumber 'F3))
	       (list 'PERF-09 (ew-keynumber 'G3))
	       (list 'PERF-10 (ew-keynumber 'A3))
	       (list 'PERF-11 (ew-keynumber 'B3))
	       (list 'PERF-12 (ew-keynumber 'C4))
	       (list 'PERF-13 (ew-keynumber 'D4))
	       (list 'PERF-14 (ew-keynumber 'E4))
	       (list 'PERF-15 (ew-keynumber 'F4))
	       (list 'PERF-16 (ew-keynumber 'G4))
	       (list 'PERF-17 (ew-keynumber 'A4))
	       (list 'PERF-18 (ew-keynumber 'B4))
	       (list 'PERF-19 (ew-keynumber 'C5))
	       (list 'PERF-20 (ew-keynumber 'D5))
	       (list 'PERF-21 (ew-keynumber 'E5))
	       (list 'PERF-22 (ew-keynumber 'F5))
	       (list 'PERF-23 (ew-keynumber 'G5))
	       (list 'PERF-24 (ew-keynumber 'A5))
	       (list 'PERF-25 (ew-keynumber 'B5))
	       (list 'PERF-26 (ew-keynumber 'C6))
	       (list 'PERF-27 (ew-keynumber 'D6))
	       (list 'PERF-28 (ew-keynumber 'E6))
	       (list 'PERF-29 (ew-keynumber 'F6)))))
  (setf (gethash '12-ledombe remarks-table) "SD3 Big Drums Remo NSL Tubano LaDome 12in")
  (sd3-instrument tubano ew-sd3-bigdrums keymap-table remarks-table)
  (sd3-query ?tubano 'tubano remarks-table) )
 
