;;;; CYCO plugins sj eastwest sd3 metals berimbau.lisp
;;;;
;;;; Variations: AF B
;;;;

(param berimbau nil)

(let ((keymap-table (make-hash-table))
      (remark-table (make-hash-table)))
  (setf (gethash 'AF keymap-table)
	(symbolic-keynumber-map
	 (list
	   (list 'MULTI-HIT-1 (ew-keynumber 'C1 ))
	   (list 'MULTI-HIT-2 (ew-keynumber 'D1 ))
	   (list 'MULTI-HIT-3 (ew-keynumber 'E1 ))
	   (list 'MULTI-HIT-4 (ew-keynumber 'F1 ))
	   (list 'MULTI-HIT-5 (ew-keynumber 'G1 ))
	   (list 'MULTI-HIT-6 (ew-keynumber 'A1 ))
	   (list 'MULTI-HIT-7 (ew-keynumber 'B1 ))
	   (list 'HIT  (ew-keynumber 'C2 ))
	   (list 'FX-1 (ew-keynumber 'D2 ))
	   (list 'FX-2 (ew-keynumber 'E2 ))
	   (list 'FX-3 (ew-keynumber 'F2 ))
	   (list 'FX-4 (ew-keynumber 'G2 ))
	   (list 'FX-5 (ew-keynumber 'A2 ))
	   (list 'FX-6 (ew-keynumber 'B2 ))
	   (list 'PERF-01 (ew-keynumber 'C3 ))
	   (list 'PERF-02 (ew-keynumber 'D3 ))
	   (list 'PERF-03 (ew-keynumber 'E3 ))
	   (list 'PERF-04 (ew-keynumber 'F3 ))
	   (list 'PERF-05 (ew-keynumber 'G3 ))
	   (list 'PERF-06 (ew-keynumber 'A3 ))
	   (list 'PERF-07 (ew-keynumber 'B3 ))
	   (list 'PERF-08 (ew-keynumber 'C4 ))
	   (list 'PERF-09 (ew-keynumber 'D4 ))
	   (list 'PERF-10 (ew-keynumber 'E4 ))
	   (list 'PERF-11 (ew-keynumber 'F4 ))
	   (list 'PERF-12 (ew-keynumber 'G4 ))
	   (list 'PERF-13 (ew-keynumber 'A4 ))
	   (list 'PERF-14 (ew-keynumber 'B4 ))
	   (list 'PERF-15 (ew-keynumber 'C5 )))))
  (setf (gethash 'AF remark-table) "SD3 Metals Berimbau Ab")
  (setf (gethash 'B keymap-table)
	(symbolic-keynumber-map
	 (list
	  (list 'MULTI-HIT (ew-keynumber 'C1 ))
	  (list 'FRAME-HIT-1 (ew-keynumber 'D1 ))
	  (list 'FRAME-HIT-2 (ew-keynumber 'E1 ))
	  (list 'FRAME-HIT-3 (ew-keynumber 'F1 ))
	  (list 'FRAME-HIT-4 (ew-keynumber 'G1 ))
	  (list 'FRAME-HIT-5 (ew-keynumber 'A1 ))
	  (list 'FRAME-HIT-6 (ew-keynumber 'B1 ))
	  (list 'FRAME-HIT-7 (ew-keynumber 'C2 ))
	  (list 'FRAME-HIT-8 (ew-keynumber 'D2 ))
	  (list 'CAPACA (ew-keynumber 'E2 ))
	  (list 'TIKI   (ew-keynumber 'F2 ))
	  (list 'CAPACA-ROLL-1 (ew-keynumber 'G2 ))
	  (list 'CAPACA-ROLL-2 (ew-keynumber 'A2 ))
	  (list 'CAPACA-ROLL-3 (ew-keynumber 'B2 ))
	  (list 'CAPACA-ROLL-4 (ew-keynumber 'C3 ))
	  (list 'CAPACA-ROLL-5 (ew-keynumber 'D3 ))
	  (list 'CAPACA-ROLL-6 (ew-keynumber 'E3 ))
	  (list 'CAPACA-ROLL-7 (ew-keynumber 'F3 ))
	  (list 'PERF-01 (ew-keynumber 'G3 ))
	  (list 'PERF-02 (ew-keynumber 'A3 ))
	  (list 'PERF-03 (ew-keynumber 'B3 ))
	  (list 'PERF-04 (ew-keynumber 'C4 ))
	  (list 'PERF-05 (ew-keynumber 'D4 ))
	  (list 'PERF-06 (ew-keynumber 'E4 ))
	  (list 'PERF-07 (ew-keynumber 'F4 ))
	  (list 'PERF-08 (ew-keynumber 'G4 ))
	  (list 'PERF-09 (ew-keynumber 'A4 ))
	  (list 'PERF-10 (ew-keynumber 'B4 ))
	  (list 'PERF-11 (ew-keynumber 'C5 ))
	  (list 'PERF-12 (ew-keynumber 'D5 ))
	  (list 'PERF-13 (ew-keynumber 'E5 ))
	  (list 'PERF-14 (ew-keynumber 'F5 ))
	  (list 'PERF-15 (ew-keynumber 'G5 ))
	  (list 'PERF-16 (ew-keynumber 'A5 ))
	  (list 'PERF-17 (ew-keynumber 'B5 )))))
  (setf (gethash 'B remark-table) "SD3 Metals Berimbau B")
  (sd3-instrument berimbau ew-sd3-metals keymap-table remark-table)
  (sd3-query ?berimbau 'berimbau remark-table)) 
  
