;;;; CYCO plugins sj eastwest sd3 woods redwood.lisp
;;;;

(param redwood nil)

(let ((keymap-table (make-hash-table))
      (remark-table (make-hash-table)))
  (setf
   (gethash 'full keymap-table)(symbolic-keynumber-map
				(list
				 (list 'SOFT-01 (keynumber 'C1))  
				 (list 'SOFT-02 (keynumber 'CS1)) 
				 (list 'SOFT-03 (keynumber 'D1))  
				 (list 'SOFT-04 (keynumber 'DS1)) 
				 (list 'SOFT-05 (keynumber 'E1))  
				 (list 'SOFT-06 (keynumber 'F1))  
				 (list 'SOFT-07 (keynumber 'FS1)) 
				 (list 'SOFT-08 (keynumber 'G1))  
				 (list 'SOFT-09 (keynumber 'GS1)) 
				 (list 'SOFT-10 (keynumber 'A1))  
				 (list 'SOFT-11 (keynumber 'AS1)) 
				 (list 'MED-01 (keynumber 'B1))  
				 (list 'MED-02 (keynumber 'C2))  
				 (list 'MED-03 (keynumber 'CS2)) 
				 (list 'MED-04 (keynumber 'D2))  
				 (list 'MED-05 (keynumber 'DS2)) 
				 (list 'MED-06 (keynumber 'E2))  
				 (list 'MED-07 (keynumber 'F2))  
				 (list 'MED-08 (keynumber 'FS2)) 
				 (list 'MED-09 (keynumber 'G2))  
				 (list 'MED-10 (keynumber 'GS2)) 
				 (list 'MED-11 (keynumber 'A2))  
				 (list 'MED-12 (keynumber 'AS2)) 
				 (list 'MED-13 (keynumber 'B2))  
				 (list 'MED-14 (keynumber 'C3))  
				 (list 'MED-15 (keynumber 'CS3)) 
				 (list 'MED-16 (keynumber 'D3))  
				 (list 'MED-17 (keynumber 'DS3)) 
				 (list 'MED-18 (keynumber 'E3))  
				 (list 'MED-19 (keynumber 'F3))  
				 (list 'MED-20 (keynumber 'FS3)) 
				 (list 'MED-21 (keynumber 'G3))  
				 (list 'MED-22 (keynumber 'GS3)) 
				 (list 'MED-23 (keynumber 'A3))  
				 (list 'MED-24 (keynumber 'AS3)) 
				 (list 'MED-25 (keynumber 'B3))  
				 (list 'MED-26 (keynumber 'C4))  
				 (list 'MED-27 (keynumber 'CS4)) 
				 (list 'MED-28 (keynumber 'D4))  
				 (list 'MED-29 (keynumber 'DS4)) 
				 (list 'MED-30 (keynumber 'E4))  
				 (list 'MED-31 (keynumber 'F4))  
				 (list 'MED-32 (keynumber 'FS4)) 
				 (list 'MED-33 (keynumber 'G4))  
				 (list 'LOUD-1 (keynumber 'GS5)) 
				 (list 'LOUD-2 (keynumber 'G5))))  
   (gethash 'perf keymap-table)(circular-keynumber-map
				(ew-keynumber 'c1)
				(ew-keynumber 'd4)))
  (setf
   (gethash 'full remark-table) "SD3 Woods Redwood Tree fullmix"
   (gethash 'perf remark-table) "SD3 Woods Redwood Tree PerfFx")
  (sd3-instrument redwood ew-sd3-woods keymap-table remark-table)
  (sd3-query ?redwood 'redwood remark-table)) 
   
       
