;;;; CYCO plugins sj eastwest sd3 shakers remo-shaker.lisp
;;;;


(param gourd-rattle nil)

(let ((keymap-table (make-hash-table))
      (remarks-table (make-hash-table)))
  (setf (gethash 1 keymap-table)
	(symbolic-keynumber-map (list (list 'HIT-1 (ew-keynumber 'C1 ))
				      (list 'HIT-2 (ew-keynumber 'D1 ))
				      (list 'HIT-3 (ew-keynumber 'E1 ))
				      (list 'PERF-01 (ew-keynumber 'F1 ))
				      (list 'PERF-02 (ew-keynumber 'G1 ))
				      (list 'PERF-03 (ew-keynumber 'A1 ))
				      (list 'PERF-04 (ew-keynumber 'B1 ))
				      (list 'PERF-05 (ew-keynumber 'C2 ))
				      (list 'PERF-06 (ew-keynumber 'D2 ))
				      (list 'PERF-07 (ew-keynumber 'E2 ))
				      (list 'PERF-08 (ew-keynumber 'F2 ))
				      (list 'PERF-09 (ew-keynumber 'G2 ))
				      (list 'PERF-10 (ew-keynumber 'A2 ))
				      (list 'PERF-11 (ew-keynumber 'B2 ))
				      (list 'PERF-12 (ew-keynumber 'C3 )))))
  (setf (gethash 1 remarks-table) "SD3 Shakers Small Gourd 1   RR 4")
  (setf (gethash 2 keymap-table)
	(symbolic-keynumber-map (list (list 'HIT-1 (ew-keynumber 'C1 ))
				      (list 'HIT-2 (ew-keynumber 'D1 ))
				      (list 'HIT-3 (ew-keynumber 'E1 ))
				      (list 'HIT-4 (ew-keynumber 'F1 ))
				      (list 'HIT-5 (ew-keynumber 'G1 ))
				      (list 'PERF-1 (ew-keynumber 'A1 ))
				      (list 'PERF-2 (ew-keynumber 'B1 ))
				      (list 'PERF-3 (ew-keynumber 'C2 ))
				      (list 'PERF-4 (ew-keynumber 'D2 ))
				      (list 'PERF-5 (ew-keynumber 'E2 ))
				      (list 'PERF-6 (ew-keynumber 'F2 ))
				      (list 'PERF-7 (ew-keynumber 'G2 ))
				      (list 'ROLL-1 (ew-keynumber 'A2 ))
				      (list 'ROLL-2 (ew-keynumber 'B2 ))
				      (list 'ROLL-3 (ew-keynumber 'C3 ))
				      (list 'ROLL-4 (ew-keynumber 'D3 ))
				      (list 'ROLL-5 (ew-keynumber 'E3 ))
				      (list 'ROLL-6 (ew-keynumber 'F3 ))
				      (list 'ROLL-7 (ew-keynumber 'G3 ))
				      (list 'ROLL-8 (ew-keynumber 'A3 ))
				      (list 'ROLL-9 (ew-keynumber 'B3 )))))
  (setf (gethash 2 remarks-table) "SD3 Shakers Small Gourd 2   RR 4")
  (sd3-instrument gourd-rattle ew-sd3-shakers keymap-table remarks-table)
  (sd3-query ?gourd-rattle 'gourd-rattle remarks-table))
  
