;;;; CYCO plugins sj eastwest sd3 smalldrums bongos.lisp

(param bongo nil)

(let ((keymap-table (make-hash-table))
      (remark-table (make-hash-table)))
  (setf (gethash 'bauer keymap-table)(symbolic-keynumber-map
				      (list 
				       (list 'LOW-RIM           (ew-keynumber 'C1 ))
				       (list 'LOW-RIM-MUTE      (ew-keynumber 'D1 ))
				       (list 'LOW-CENTER-DOUBLE (ew-keynumber 'E1 ))
				       (list 'LOW-CENTER        (ew-keynumber 'F1 ))
				       (list 'LOW-CENTER-MUTE   (ew-keynumber 'G1 ))
				       (list 'LOW-CENTER-SCRAPE (ew-keynumber 'A1 ))
				       (list 'LOW-ROLL-P        (ew-keynumber 'B1 ))
				       (list 'LOW-ROLL-MP       (ew-keynumber 'C2 ))
				       (list 'LOW-ROLL-MF       (ew-keynumber 'D2 ))
				       (list 'LOW-ROLL-F        (ew-keynumber 'E2 ))
				       (list 'LOW-RIM-SHORT     (ew-keynumber 'F2 ))
				       (list 'LOW-RIM-LONG      (ew-keynumber 'G2 ))
				       (list 'HIGH-RIM          (ew-keynumber 'C3 ))
				       (list 'HIGH-RIM-MUTE      (ew-keynumber 'D3 ))
				       (list 'HIGH-CENTER-DOUBLE (ew-keynumber 'E3 ))
				       (list 'HIGH-CENTER        (ew-keynumber 'F3 ))
				       (list 'HIGH-CENTER-MUTE   (ew-keynumber 'G3 ))
				       (list 'HIGH-CENTER-SCRAPE (ew-keynumber 'A3 ))
				       (list 'HIGH-ROLL-P        (ew-keynumber 'B3 ))
				       (list 'HIGH-ROLL-MP       (ew-keynumber 'C4 ))
				       (list 'HIGH-ROLL-MF       (ew-keynumber 'D4 ))
				       (list 'HIGH-ROLL-F        (ew-keynumber 'E4 ))
				       (list 'HIGH-RIM-SHORT     (ew-keynumber 'F4 ))
				       (list 'HIGH-RIM-LONG      (ew-keynumber 'G4 ))))
	(gethash 'tri-cuba keymap-table)(symbolic-keynumber-map
					 (list
					  (list 'OPEN-1 (ew-keynumber 'C1 ))
					  (list 'OPEN-2 (ew-keynumber 'D1 ))
					  (list 'BASS   (ew-keynumber 'E1 ))
					  (list 'MUTE   (ew-keynumber 'F1 ))
					  (list 'FLAM   (ew-keynumber 'G1 ))
					  (list 'ROLL-1 (ew-keynumber 'A1 ))
					  (list 'OPEN-3 (ew-keynumber 'B1 ))
					  (list 'OPEN-4 (ew-keynumber 'C2 ))
					  (list 'SLAP-1 (ew-keynumber 'D2 ))
					  (list 'SLAP-2 (ew-keynumber 'E2 ))
					  (list 'SLAP-3 (ew-keynumber 'F2 ))
					  (list 'ROLL-2 (ew-keynumber 'G2 ))
					  (list 'ROLL-3 (ew-keynumber 'A2 ))
					  (list 'PERF   (ew-keynumber 'B2 ))
					  (list 'SCRAPE-1 (ew-keynumber 'C3 ))
					  (list 'SCRAPE-2 (ew-keynumber 'D3 ))
					  (list 'SCRAPE-3 (ew-keynumber 'E3 ))
					  (list 'SCRAPE-4 (ew-keynumber 'F3 ))
					  (list 'SCRAPE-5 (ew-keynumber 'G3 ))
					  (list 'SCRAPE-6 (ew-keynumber 'A3 ))
					  (list 'SCRAPE-7 (ew-keynumber 'B3 ))
					  (list 'SCRAPE-8 (ew-keynumber 'C4 )))))
  (setf (gethash 'bauer remark-table) "SD3 Small Drums  Bongo Bauer"
	(gethash 'tri-cuba remark-table) "SD3 Small Drums  Tri Bongo Cuba")
  
  (sd3-instrument bongo ew-sd3-smalldrums keymap-table remark-table)
  (sd3-query ?bongo 'bongo remark-table)) 
