;;;; CYCO plugins sj eastwest sd3 smalldrums udu
;;;;

(param udu nil)

;; ***MISSING*** india-rr variation
;;
(let ((keymap-table (make-hash-table))
      (remark-table (make-hash-table)))
  (setf
   (gethash 'india keymap-table) (symbolic-keynumber-map
				  (list
				   (list 'OPEN-1 (ew-keynumber 'C1 ))
				   (list 'OPEN-2 (ew-keynumber 'D1 ))
				   (list 'OPEN-3 (ew-keynumber 'E1 ))
				   (list 'OPEN-4 (ew-keynumber 'F1 ))
				   (list 'OPEN-5 (ew-keynumber 'G1 ))
				   (list 'OPEN-6 (ew-keynumber 'A1 ))
				   (list 'OPEN-7 (ew-keynumber 'B1 ))
				   (list 'SHELL-1 (ew-keynumber 'C2 ))
				   (list 'SHELL-2 (ew-keynumber 'D2 ))
				   (list 'SHELL-3 (ew-keynumber 'E2 ))
				   (list 'SHELL-4 (ew-keynumber 'F2 ))
				   (list 'SHELL-5 (ew-keynumber 'G2 ))
				   (list 'SHELL-6 (ew-keynumber 'A2 ))
				   (list 'SHELL-7 (ew-keynumber 'B2 ))
				   (list 'SHELL-MUTE-1 (ew-keynumber 'C3 ))
				   (list 'SHELL-MUTE-2 (ew-keynumber 'D3 ))
				   (list 'SHELL-MUTE-3 (ew-keynumber 'E3 ))
				   (list 'SHELL-MUTE-4 (ew-keynumber 'F3 ))
				   (list 'SHELL-MUTE-5 (ew-keynumber 'G3 ))
				   (list 'SHELL-MUTE-6 (ew-keynumber 'A3 ))
				   (list 'SHELL-MUTE-7 (ew-keynumber 'B3 ))
				   (list 'FLAM-1 (ew-keynumber 'C4 ))
				   (list 'FLAM-2 (ew-keynumber 'D4 ))
				   (list 'FLAM-3 (ew-keynumber 'E4 ))
				   (list 'FLAM-4 (ew-keynumber 'F4 ))
				   (list 'FLAM-5 (ew-keynumber 'G4 ))
				   (list 'FLAM-6 (ew-keynumber 'A4 ))
				   (list 'FLAM-7 (ew-keynumber 'B4 ))
				   (list 'BEND-1 (ew-keynumber 'C5 ))
				   (list 'BEND-2 (ew-keynumber 'D5 ))
				   (list 'BEND-3 (ew-keynumber 'E5 ))
				   (list 'BEND-4 (ew-keynumber 'F5 ))
				   (list 'BEND-5 (ew-keynumber 'G5 ))
				   (list 'BEND-6 (ew-keynumber 'A5 ))
				   (list 'BEND-7 (ew-keynumber 'B5 ))))
				   
   (gethash 'ghana keymap-table) (symbolic-keynumber-map
				  (list
				   (list 'OPEN-1 (ew-keynumber 'C1 ))
				   (list 'OPEN-2 (ew-keynumber 'D1 ))
				   (list 'OPEN-3 (ew-keynumber 'E1 ))
				   (list 'OPEN-4 (ew-keynumber 'F1 ))
				   (list 'OPEN-5 (ew-keynumber 'G1 ))
				   (list 'OPEN-6 (ew-keynumber 'A1 ))
				   (list 'SHELL-1 (ew-keynumber 'B1 ))
				   (list 'SHELL-2 (ew-keynumber 'C2 ))
				   (list 'SHELL-3 (ew-keynumber 'D2 ))
				   (list 'SHELL-4 (ew-keynumber 'E2 ))
				   (list 'SHELL-5 (ew-keynumber 'F2 ))
				   (list 'SHELL-6 (ew-keynumber 'G2 ))
				   (list 'SHELL-7 (ew-keynumber 'A2 ))
				   (list 'SHELL-MUTE-1 (ew-keynumber 'B2 ))
				   (list 'SHELL-MUTE-2 (ew-keynumber 'C3 ))
				   (list 'SHELL-MUTE-3 (ew-keynumber 'D3 ))
				   (list 'SHELL-MUTE-4 (ew-keynumber 'E3 ))
				   (list 'SHELL-MUTE-5 (ew-keynumber 'F3 ))
				   (list 'SHELL-MUTE-6 (ew-keynumber 'G3 ))
				   (list 'SHELL-MUTE-7 (ew-keynumber 'A3 ))
				   (list 'SHELL-FLAM-1 (ew-keynumber 'B3 ))
				   (list 'SHELL-FLAM-2 (ew-keynumber 'C4 ))
				   (list 'SHELL-FLAM-3 (ew-keynumber 'D4 ))
				   (list 'SHELL-FLAM-4 (ew-keynumber 'E4 ))
				   (list 'SHELL-FLAM-5 (ew-keynumber 'F4 ))
				   (list 'SHELL-FLAM-6 (ew-keynumber 'G4 ))
				   (list 'SHELL-FLAM-7 (ew-keynumber 'A4 ))
				   (list 'BEND-1 (ew-keynumber 'G5 ))
				   (list 'BEND-2 (ew-keynumber 'A5 ))
				   (list 'BEND-3 (ew-keynumber 'B5 ))
				   (list 'BEND-4 (ew-keynumber 'C6 ))
				   (list 'ROLL-1 (ew-keynumber 'D6 ))
				   (list 'ROLL-2 (ew-keynumber 'E6 ))
				   (list 'ROLL-3 (ew-keynumber 'F6 ))
				   (list 'ROLL-4 (ew-keynumber 'G6 ))))
   (gethash 'ghana-rr keymap-table) (symbolic-keynumber-map
				     (list 
				      (list 'OPEN (ew-keynumber 'C1 ))
				      (list 'BEND (ew-keynumber 'D1 ))
				      (list 'BEND-SHORT (ew-keynumber 'E1 ))
				      (list 'SHELL (ew-keynumber 'F1 ))
				      (list 'SHELL-MUTE (ew-keynumber 'G1 ))
				      (list 'SHELL-FLAM (ew-keynumber 'A1 ))
				      (list 'ROLL (ew-keynumber 'B1 ))))
   (gethash 'pakistan keymap-table) (symbolic-keynumber-map
				     (list
				      (list 'OPEN-1 (ew-keynumber 'C1 ))
				      (list 'OPEN-2 (ew-keynumber 'D1 ))
				      (list 'OPEN-3 (ew-keynumber 'E1 ))
				      (list 'OPEN-4 (ew-keynumber 'F1 ))
				      (list 'SHELL-1 (ew-keynumber 'G1 ))
				      (list 'SHELL-2 (ew-keynumber 'A1 ))
				      (list 'SHELL-3 (ew-keynumber 'B1 ))
				      (list 'SHELL-4 (ew-keynumber 'C2 ))
				      (list 'SHELL-MUTE-1 (ew-keynumber 'D2 ))
				      (list 'SHELL-MUTE-2 (ew-keynumber 'E2 ))
				      (list 'SHELL-MUTE-3 (ew-keynumber 'F2 ))
				      (list 'SHELL-MUTE-4 (ew-keynumber 'G2 ))
				      (list 'SHELL-MUTE-5 (ew-keynumber 'A2 ))
				      (list 'SHELL-MUTE-6 (ew-keynumber 'B2 ))
				      (list 'HIGH-OPEN-1 (ew-keynumber 'C3 ))
				      (list 'HIGH-OPEN-2 (ew-keynumber 'D3 ))
				      (list 'HIGH-OPEN-3 (ew-keynumber 'E3 ))
				      (list 'HIGH-OPEN-4 (ew-keynumber 'F3 ))
				      (list 'HIGH-OPEN-5 (ew-keynumber 'G3 ))
				      (list 'HIGH-OPEN-6 (ew-keynumber 'A3 ))
				      (list 'HIGH-SHELL-1 (ew-keynumber 'B3 ))
				      (list 'HIGH-SHELL-2 (ew-keynumber 'C4 ))
				      (list 'HIGH-SHELL-3 (ew-keynumber 'D4 ))
				      (list 'HIGH-SHELL-4 (ew-keynumber 'E4 ))
				      (list 'HIGH-SHELL-5 (ew-keynumber 'F4 ))
				      (list 'HIGH-SHELL-6 (ew-keynumber 'G4 ))
				      (list 'HIGH-SHELL-7 (ew-keynumber 'A4 ))
				      (list 'HIGH-MUTE-1 (ew-keynumber 'B4 ))
				      (list 'HIGH-MUTE-2 (ew-keynumber 'C5 ))
				      (list 'HIGH-MUTE-3 (ew-keynumber 'D5 ))
				      (list 'HIGH-MUTE-4 (ew-keynumber 'E5 ))
				      (list 'HIGH-MUTE-5 (ew-keynumber 'F5 ))
				      (list 'BEND-1 (ew-keynumber 'B4 ))
				      (list 'BEND-2 (ew-keynumber 'C5 ))
				      (list 'BEND-3 (ew-keynumber 'D5 ))
				      (list 'BEND-4 (ew-keynumber 'E5 ))
				      (list 'BEND-5 (ew-keynumber 'F5 ))
				      (list 'HIT-BEND-1 (ew-keynumber 'C6 ))
				      (list 'HIT-BEND-2 (ew-keynumber 'D6 ))
				      (list 'HIT-BEND-3 (ew-keynumber 'E6 ))
				      (list 'HIT-BEND-4 (ew-keynumber 'F6 ))
				      (list 'HIT-BEND-5 (ew-keynumber 'G6 ))
				      (list 'HIT-BEND-6 (ew-keynumber 'A6 ))
				      (list 'HIT-BEND-7 (ew-keynumber 'B6 ))
				      (list 'HIT-BEND-8 (ew-keynumber 'C7 )))))
  (setf
   (gethash 'india remark-table) "SD3 SmallDrums  Ubu India"
   (gethash 'ghana remark-table) "SD3 SmallDrums  Ubu Large Ghana"
   (gethash 'ghana-rr remark-table) "SD3 SmallDrums  Ubu Large Ghana RR"
   (gethash 'pakistan remark-table) "SD3 SmallDrums  Ubu Pakistan")
                                      
  (sd3-instrument udu ew-sd3-smalldrums keymap-table remark-table)
  (sd3-query ?udu 'udu remark-table)) 
