;;;; CYCO plugins sj eastwest sd3 bigdrums cajon.lisp
;;;;
;;;; ew-sd3-bigdrums
;;;;  |
;;;;  +-- cajon
;;;;        black
;;;;        remo
;;;;

(param cajon nil)

(let ((keymap-table (make-hash-table))
      (remarks-table (make-hash-table)))
  (setf (gethash 'black keymap-table)
	(symbolic-keynumber-map
	 (list (list 'BASS-RH     (ew-keynumber 'C1))
	       (list 'CENTER-RH   (ew-keynumber 'D1))
	       (list 'EDGE-LH     (ew-keynumber 'E1))
	       (list 'SLAP-RH     (ew-keynumber 'F1))
	       (list 'CORNER-LH   (ew-keynumber 'G1))
	       (list 'CORNER-FLAM (ew-keynumber 'A1))
	       (list 'VELROLL-1 (ew-keynumber 'B1))
	       (list 'VELROLL-2 (ew-keynumber 'C2))
	       (list 'NVROLL-01 (ew-keynumber 'D2))
	       (list 'NVROLL-02 (ew-keynumber 'E2))
	       (list 'NVROLL-03 (ew-keynumber 'F2))
	       (list 'NVROLL-04 (ew-keynumber 'G2))
	       (list 'NVROLL-05 (ew-keynumber 'A2))
	       (list 'NVROLL-06 (ew-keynumber 'B2))
	       (list 'NVROLL-07 (ew-keynumber 'C3))
	       (list 'NVROLL-08 (ew-keynumber 'D3))
	       (list 'NVROLL-09 (ew-keynumber 'E3))
	       (list 'NVROLL-10 (ew-keynumber 'F3))
	       (list 'NVROLL-11 (ew-keynumber 'G3))
	       (list 'NVROLL-12 (ew-keynumber 'A3))
	       (list 'NVROLL-13 (ew-keynumber 'B3))
	       (list 'BASS-NVROLL-01 (ew-keynumber 'C4))
	       (list 'BASS-NVROLL-02 (ew-keynumber 'D4))
	       (list 'BASS-NVROLL-03 (ew-keynumber 'E4))
	       (list 'BASS-NVROLL-04 (ew-keynumber 'F4))
	       (list 'BASS-NVROLL-05 (ew-keynumber 'G4))
	       (list 'BASS-NVROLL-06 (ew-keynumber 'A4))
	       (list 'BASS-NVROLL-07 (ew-keynumber 'B4))
	       (list 'BASS-NVROLL-08 (ew-keynumber 'C5))
	       (list 'BASS-NVROLL-09 (ew-keynumber 'D5))
	       (list 'BASS-NVROLL-10 (ew-keynumber 'E5))
	       (list 'BASS-NVROLL-11 (ew-keynumber 'F5))
	       (list 'BASS-NVROLL-12 (ew-keynumber 'G5))
	       (list 'PERF-01 (ew-keynumber 'A5))
	       (list 'PERF-02 (ew-keynumber 'B5))
	       (list 'PERF-03 (ew-keynumber 'C6))
	       (list 'PERF-04 (ew-keynumber 'D6))
	       (list 'PERF-05 (ew-keynumber 'E6))
	       (list 'PERF-06 (ew-keynumber 'F6))
	       (list 'PERF-07 (ew-keynumber 'G6))
	       (list 'PERF-08 (ew-keynumber 'A6))
	       (list 'PERF-09 (ew-keynumber 'B6))
	       (list 'PERF-10 (ew-keynumber 'C7)))))
  (setf (gethash 'black remarks-table) "SD3 Big Drums Cajon Black Custom")
  (setf (gethash 'remo keymap-table)
	(symbolic-keynumber-map
	 (list (list 'CORNER-RH   (ew-keynumber 'F1))
	       (list 'CORNER-FLAM (ew-keynumber 'G1))
	       (list 'ROLLS-01 (ew-keynumber 'A2))
	       (list 'ROLLS-02 (ew-keynumber 'B2))
	       (list 'ROLLS-03 (ew-keynumber 'C3))
	       (list 'ROLLS-04 (ew-keynumber 'D3))
	       (list 'ROLLS-05 (ew-keynumber 'E3))
	       (list 'ROLLS-06 (ew-keynumber 'F3))
	       (list 'ROLLS-07 (ew-keynumber 'G3))
	       (list 'ROLLS-08 (ew-keynumber 'A3))
	       (list 'ROLLS-09 (ew-keynumber 'B3))
	       (list 'ROLLS-19 (ew-keynumber 'C4))
	       (list 'ROLLS-11 (ew-keynumber 'D4))
	       (list 'PERF-01  (ew-keynumber 'E4))
	       (list 'PERF-02  (ew-keynumber 'F4))
	       (list 'PERF-03  (ew-keynumber 'G4))
	       (list 'PERF-04  (ew-keynumber 'A4))
	       (list 'PERF-05  (ew-keynumber 'B4))
	       (list 'PERF-06  (ew-keynumber 'C5))
	       (list 'PERF-07  (ew-keynumber 'D5))
	       (list 'PERF-08  (ew-keynumber 'E5))
	       (list 'PERF-09  (ew-keynumber 'F5))
	       (list 'PERF-10  (ew-keynumber 'G5))
	       (list 'PERF-11  (ew-keynumber 'A5))
	       (list 'PERF-12  (ew-keynumber 'B5))
	       (list 'PERF-13  (ew-keynumber 'C6))
	       (list 'PERF-14  (ew-keynumber 'D6))
	       (list 'PERF-15  (ew-keynumber 'E6)))))
  (setf (gethash 'remo remarks-table) "SD3 Big Drums Cajon Cajon Remo")
  (sd3-instrument cajon ew-sd3-bigdrums keymap-table remarks-table)
  (sd3-query ?cajon 'cajon remarks-table))
 
