;;;; CYCO plugins sj eastwest sd3 frame-drum.lisp
;;;;
;;;; Includes frame drums, "table drum", tanbourines & "ocean drum"
;;;;
;;;; ew-sd3-bigdrums
;;;;  |
;;;;  +-- frame-drum
;;;;          daf-turkey
;;;;          8-inch
;;;;          10-inch
;;;;          12-inch
;;;;          22-inch
;;;;          table-drum
;;;;          ocean-drum
;;;;          12-inch-tambourine
;;;;          stick-tambourine
;;;;          16-inch-tambourine
;;;;          pandero
;;;;

(param frame-drum nil)

(let ((keymap-table (make-hash-table))
      (remarks-table (make-hash-table)))
  (setf (gethash 'daf-turkey keymap-table)
	(symbolic-keynumber-map
	 (list (list 'CENTER        (ew-keynumber 'C1))
	       (list 'EDGE          (ew-keynumber 'D1))
	       (list 'MUTE          (ew-keynumber 'E1))
	       (list 'SLIDE         (ew-keynumber 'F1))
	       (list 'FINGER-ROLL-1 (ew-keynumber 'G1))
	       (list 'FINGER-ROLL-2 (ew-keynumber 'A1))
	       (list 'FINGER-ROLL-3 (ew-keynumber 'B1))
	       (list 'SHORT-SHAKE-1 (ew-keynumber 'C2))
	       (list 'SHORT-SHAKE-2 (ew-keynumber 'D2))
	       (list 'LONG-SHAKE-1  (ew-keynumber 'E2))
	       (list 'LONG-SHAKE-2  (ew-keynumber 'F2))
	       (list 'LONG-SHAKE-3  (ew-keynumber 'G2))
	       (list 'PERF-1        (ew-keynumber 'A2))
	       (list 'PERF-2        (ew-keynumber 'B2)))))
  (setf (gethash 'daf-turkey remarks-table) "SD3 Big Drums Daf Turkey")
  (setf (gethash '22-inch keymap-table)
	(symbolic-keynumber-map
	 (list (list 'OPEN-LH   (ew-keynumber 'C1))
	       (list 'OPEN-RH   (ew-keynumber 'D1))
	       (list 'FLAM      (ew-keynumber 'E1))
	       (list 'RIM-LH    (ew-keynumber 'F1))
	       (list 'RIM-RH    (ew-keynumber 'G1))
	       (list 'EDGE-FLAM (ew-keynumber 'A1))
	       (list 'SNAP-0    (ew-keynumber 'B1))
	       (list 'SNAP-1    (ew-keynumber 'C2))
	       (list 'SNAP-2    (ew-keynumber 'D2))
	       (list 'SNAP-3    (ew-keynumber 'E2))
	       (list 'DOUBLE-SNAP-1 (ew-keynumber 'F2))
	       (list 'DOUBLE-SNAP-2 (ew-keynumber 'G2))
	       (list 'PERF-0    (ew-keynumber 'A2))
	       (list 'PERF-1    (ew-keynumber 'B2))
	       (list 'PERF-2    (ew-keynumber 'C3))
	       (list 'PERF-3    (ew-keynumber 'D3))
	       (list 'PERF-4    (ew-keynumber 'E3))
	       (list 'PERF-5    (ew-keynumber 'F3))
	       (list 'PERF-6    (ew-keynumber 'G3))
	       (list 'PERF-7    (ew-keynumber 'A3)))))
  (setf (gethash '22-inch remarks-table) "SD3 Big Drums Frame Drum 22in Rwnaissance")
  (setf (gethash '16-inch-tambourine keymap-table)
	(symbolic-keynumber-map
	 (list (list 'OPEN         (ew-keynumber 'C1))
	       (list 'JUNGLE       (ew-keynumber 'D1))
	       (list 'THUMB-CENTER (ew-keynumber 'E1))
	       (list 'SLAP-CENTER  (ew-keynumber 'F1))
	       (list 'SLAP-JUNGLE  (ew-keynumber 'G1))
	       (list 'RIM          (ew-keynumber 'A1))
	       (list 'ROLLS-1      (ew-keynumber 'B1))
	       (list 'ROLLS-2      (ew-keynumber 'C2))
	       (list 'ROLLS-3      (ew-keynumber 'D2))
	       (list 'ROLLS-4      (ew-keynumber 'E3))
	       (list 'ROLLS-5      (ew-keynumber 'F2))
	       (list 'ROLLS-6      (ew-keynumber 'G2))
	       (list 'ROLLS-7      (ew-keynumber 'A2)))))

  (setf (gethash '16-inch-tambourine remarks-table) "SD3 Big Drums Tambourine 16in Dbl")
  (setf (gethash 'table-drum keymap-table)
	(symbolic-keynumber-map
	 (list (list 'GONG-1       (ew-keynumber 'C1))
	       (list 'GONG-2       (ew-keynumber 'D1))
	       (list 'GONG-STICK-1 (ew-keynumber 'E1))
	       (list 'GONG-STICK-2 (ew-keynumber 'F1))
	       (list 'GONG-STICK-3 (ew-keynumber 'G1))
	       (list 'GONG-STICK-4 (ew-keynumber 'A1))
	       (list 'GONG-STICK-5 (ew-keynumber 'B1))
	       (list 'LIGHT-MALLET (ew-keynumber 'C2))
	       (list 'SMALL-MALLET (ew-keynumber 'D2))
	       (list 'MEDIUM-MALLET-LH (ew-keynumber 'E2))
	       (list 'MEDIUM-MALLET-RH (ew-keynumber 'F2))
	       (list 'STICK-1      (ew-keynumber 'G2))
	       (list 'STICK-2      (ew-keynumber 'A2))
	       (list 'STICK-3      (ew-keynumber 'B2))
	       (list 'REPS-1       (ew-keynumber 'C3))
	       (list 'REPS-2       (ew-keynumber 'D3))
	       (list 'CENTER       (ew-keynumber 'E3))
	       (list 'OFF-CENTER   (ew-keynumber 'F3))
	       (list 'EDGE         (ew-keynumber 'G3))
	       (list 'REPS-3       (ew-keynumber 'A3))
	       (list 'PERF-1       (ew-keynumber 'B3))
	       (list 'PERF-2       (ew-keynumber 'C4))
	       (list 'PERF-3       (ew-keynumber 'D4))
	       (list 'PERF-4       (ew-keynumber 'E4)))))
  (setf (gethash 'table-drum remarks-table) "SD3 Big Drums Remo Table Drum")
  (setf (gethash 'ocean-drum keymap-table)
	(symbolic-keynumber-map
	 (list (list 'EDGE-1  (ew-keynumber 'C1))
	       (list 'EDGE-2  (ew-keynumber 'D1))
	       (list 'EDGE-3  (ew-keynumber 'E1))
	       (list 'EDGE-4  (ew-keynumber 'F1))
	       (list 'NO-RR-1 (ew-keynumber 'G1))
	       (list 'NO-RR-2 (ew-keynumber 'A1))
	       (list 'NO-RR-3 (ew-keynumber 'B1))
	       (list 'NO-RR-4 (ew-keynumber 'C2))
	       (list 'NO-RR-5 (ew-keynumber 'D2))
	       (list 'NO-RR-6 (ew-keynumber 'E2))
	       (list 'ROLLS-1 (ew-keynumber 'F2))
	       (list 'ROLLS-2 (ew-keynumber 'G2))
	       (list 'ROLLS-3 (ew-keynumber 'A2))
	       (list 'ROLLS-4 (ew-keynumber 'B2))
	       (list 'PERF-1  (ew-keynumber 'C3))
	       (list 'PERF-2  (ew-keynumber 'D3))
	       (list 'PERF-3  (ew-keynumber 'E3)))))
  (setf (gethash 'ocean-drum remarks-table) "SD3 Big Drums  Remo 22in Ocean Drum")
  (setf (gethash '8-inch keymap-table)
	(symbolic-keynumber-map
	 (list (list 'OPEN    (ew-keynumber 'C1))
	       (list 'EDGE-1  (ew-keynumber 'D1))
	       (list 'EDGE-2  (ew-keynumber 'E1))
	       (list 'TONE    (ew-keynumber 'F1))
	       (list 'ROLL-01 (ew-keynumber 'G1))
	       (list 'ROLL-02 (ew-keynumber 'A1))
	       (list 'ROLL-03 (ew-keynumber 'B1))
	       (list 'ROLL-04 (ew-keynumber 'C2))
	       (list 'ROLL-05 (ew-keynumber 'D2))
	       (list 'ROLL-06 (ew-keynumber 'E2))
	       (list 'ROLL-07 (ew-keynumber 'F2))
	       (list 'ROLL-08 (ew-keynumber 'G2))
	       (list 'ROLL-09 (ew-keynumber 'A2))
	       (list 'ROLL-10 (ew-keynumber 'B2))
	       (list 'ROLL-11 (ew-keynumber 'C3))
	       (list 'ROLL-12 (ew-keynumber 'D3))
	       (list 'ROLL-13 (ew-keynumber 'E3))
	       (list 'PERF-1  (ew-keynumber 'F3))
	       (list 'PERF-2  (ew-keynumber 'G3))
	       (list 'PERF-3  (ew-keynumber 'A3))
	       (list 'PERF-4  (ew-keynumber 'B3))
	       (list 'PERF-5  (ew-keynumber 'C4))
	       (list 'PERF-6  (ew-keynumber 'D4))
	       (list 'PERF-7  (ew-keynumber 'E4))
	       (list 'PERF-8  (ew-keynumber 'F4)))))
  (setf (gethash '8-inch remarks-table) "SD3 Small Drums  Frame Drum 8in Iran")
  (setf (gethash '10-inch keymap-table)
	(symbolic-keynumber-map
	 (list (list 'OPEN    (ew-keynumber 'C1))
	       (list 'EDGE    (ew-keynumber 'D1))
	       (list 'RIM     (ew-keynumber 'E1))
	       (list 'TONE    (ew-keynumber 'F1))
	       (list 'ROLL-01 (ew-keynumber 'G1))
	       (list 'ROLL-02 (ew-keynumber 'A1))
	       (list 'ROLL-03 (ew-keynumber 'B1))
	       (list 'ROLL-04 (ew-keynumber 'C2))
	       (list 'ROLL-05 (ew-keynumber 'D2))
	       (list 'ROLL-06 (ew-keynumber 'E2))
	       (list 'ROLL-07 (ew-keynumber 'F2))
	       (list 'ROLL-08 (ew-keynumber 'G2))
	       (list 'ROLL-09 (ew-keynumber 'A2))
	       (list 'ROLL-10 (ew-keynumber 'B2))
	       (list 'ROLL-11 (ew-keynumber 'C3))
	       (list 'ROLL-12 (ew-keynumber 'D3))
	       (list 'ROLL-13 (ew-keynumber 'E3))
	       (list 'ROLL-14 (ew-keynumber 'F3))
	       (list 'ROLL-15 (ew-keynumber 'G3))
	       (list 'ROLL-16 (ew-keynumber 'A3))
	       (list 'ROLL-17 (ew-keynumber 'B3))
	       (list 'ROLL-18 (ew-keynumber 'C4))
	       (list 'ROLL-19 (ew-keynumber 'D4))
	       (list 'ROLL-20 (ew-keynumber 'E4))
	       (list 'ROLL-21 (ew-keynumber 'F4))
	       (list 'ROLL-22 (ew-keynumber 'G4))
	       (list 'ROLL-23 (ew-keynumber 'A4))
	       (list 'ROLL-24 (ew-keynumber 'B4))
	       (list 'ROLL-25 (ew-keynumber 'C5))
	       (list 'ROLL-26 (ew-keynumber 'D5))
	       (list 'PERF-01 (ew-keynumber 'E5))
	       (list 'PERF-02 (ew-keynumber 'F5))
	       (list 'PERF-03 (ew-keynumber 'G5))
	       (list 'PERF-04 (ew-keynumber 'A5))
	       (list 'PERF-05 (ew-keynumber 'B5))
	       (list 'PERF-06 (ew-keynumber 'C6))
	       (list 'PERF-07 (ew-keynumber 'D6))
	       (list 'PERF-08 (ew-keynumber 'E6))
	       (list 'PERF-09 (ew-keynumber 'F6))
	       (list 'PERF-10 (ew-keynumber 'G6)))))
   (setf (gethash '10-inch remarks-table) "SD3 Small Drum  Frame Drum 10in Iran")
   (setf (gethash '12-inch keymap-table)
	 (symbolic-keynumber-map
	  (list (list 'OPEN      (ew-keynumber 'C1))
		(list 'EDGE-1    (ew-keynumber 'D1))
		(list 'EDGE-2    (ew-keynumber 'E1))
		(list 'EDGE-FLAM (ew-keynumber 'F1))
		(list 'OPEN-FLAM (ew-keynumber 'G1))
		(list 'TONE      (ew-keynumber 'A1))
		(list 'FINGER-ROLL-01 (ew-keynumber 'B1))
		(list 'FINGER-ROLL-02 (ew-keynumber 'C2))
		(list 'FINGER-ROLL-03 (ew-keynumber 'D2))
		(list 'FINGER-ROLL-04 (ew-keynumber 'E2))
		(list 'FINGER-ROLL-05 (ew-keynumber 'F2))
		(list 'FINGER-ROLL-06 (ew-keynumber 'G2))
		(list 'FINGER-ROLL-07 (ew-keynumber 'A2))
		(list 'FINGER-ROLL-08 (ew-keynumber 'B2))
		(list 'FINGER-ROLL-09 (ew-keynumber 'C3))
		(list 'FINGER-ROLL-10 (ew-keynumber 'D3))
		(list 'FINGER-ROLL-11 (ew-keynumber 'E3))
		(list 'FINGER-ROLL-12 (ew-keynumber 'F3))
		(list 'FINGER-ROLL-13 (ew-keynumber 'G3))
		(list 'FINGER-ROLL-14 (ew-keynumber 'A3))
		(list 'FINGER-ROLL-15 (ew-keynumber 'B3))
		(list 'FINGER-ROLL-16 (ew-keynumber 'C4))
		(list 'FINGER-ROLL-17 (ew-keynumber 'D4))
		(list 'FINGER-ROLL-18 (ew-keynumber 'E4))
		(list 'PERF-01 (ew-keynumber 'F4))
		(list 'PERF-02 (ew-keynumber 'G4))
		(list 'PERF-03 (ew-keynumber 'A4))
		(list 'PERF-04 (ew-keynumber 'B4))
		(list 'PERF-05 (ew-keynumber 'C5))
		(list 'PERF-06 (ew-keynumber 'D5))
		(list 'PERF-07 (ew-keynumber 'E5))
		(list 'PERF-08 (ew-keynumber 'F5))
		(list 'PERF-09 (ew-keynumber 'G5))
		(list 'PERF-10 (ew-keynumber 'A5))
		(list 'PERF-11 (ew-keynumber 'B5))
		(list 'PERF-12 (ew-keynumber 'C6))
		(list 'PERF-13 (ew-keynumber 'D6))
		(list 'PERF-14 (ew-keynumber 'E6))
		(list 'PERF-15 (ew-keynumber 'F6))
		(list 'PERF-16 (ew-keynumber 'G6))
		(list 'PERF-17 (ew-keynumber 'A6))
		(list 'PERF-18 (ew-keynumber 'B6))
		(list 'PERF-19 (ew-keynumber 'C7)))))
   (setf (gethash '12-inch remarks-table) "SD3 Small Drums Frame Drum 12in Egypt")
   (setf (gethash '12-inch-tambourine keymap-table)
	 (symbolic-keynumber-map
	  (list (list 'OPEN          (ew-keynumber 'C1))
		(list 'JINGLE-OPEN   (ew-keynumber 'D1))
		(list 'EDGE          (ew-keynumber 'E1))
		(list 'JINGLE-RIM    (ew-keynumber 'F1))
		(list 'MUTE          (ew-keynumber 'G1))
		(list 'CENTER-THUMB  (ew-keynumber 'A1))
		(list 'CENTER-SLP    (ew-keynumber 'B1))
		(list 'JINGLE-THUMB  (ew-keynumber 'C2))
		(list 'JINGLE-SLAP   (ew-keynumber 'D2))
		(list 'ROLL-JINGLE-1 (ew-keynumber 'E2))
		(list 'ROLL-JINGLE-2 (ew-keynumber 'F2))
		(list 'ROLL-JINGLE-3 (ew-keynumber 'G2))
		(list 'ROLL-JINGLE-4 (ew-keynumber 'A2))
		(list 'ROLL-JINGLE-5 (ew-keynumber 'B2))
		(list 'ROLL-JINGLE-6 (ew-keynumber 'C3))
		(list 'ROLL-JINGLE-7 (ew-keynumber 'D3))
		(list 'ROLL-JINGLE-8 (ew-keynumber 'E3))
		(list 'ROLL-OPEN-1   (ew-keynumber 'F3))
		(list 'ROLL-OPEN-2   (ew-keynumber 'G3))
		(list 'ROLL-OPEN-3   (ew-keynumber 'A3))
		(list 'ROLL-OPEN-4   (ew-keynumber 'B3))
		(list 'ROLL-OPEN-5   (ew-keynumber 'C4))
		(list 'ROLL-OPEN-6   (ew-keynumber 'D4))
		(list 'ROLL-OPEN-7   (ew-keynumber 'E4))
		(list 'ROLL-OPEN-8   (ew-keynumber 'F4))
		(list 'FAST-ROLL-1   (ew-keynumber 'G4))
		(list 'FAST-ROLL-2   (ew-keynumber 'A4))
		(list 'FAST-ROLL-3   (ew-keynumber 'B4))
		(list 'FAST-ROLL-4   (ew-keynumber 'C5))
		(list 'FAST-ROLL-5   (ew-keynumber 'D5))
		(list 'SLAP-ROLL-1   (ew-keynumber 'E5))
		(list 'SLAP-ROLL-2   (ew-keynumber 'F5))
		(list 'SLAP-ROLL-3   (ew-keynumber 'G5))
		(list 'SLAP-ROLL-4   (ew-keynumber 'A5))
		(list 'SLAP-ROLL-5   (ew-keynumber 'B5))
		(list 'SLAP-ROLL-6   (ew-keynumber 'C6))
		(list 'SLAP-ROLL-7   (ew-keynumber 'D6))
		(list 'SLAP-ROLL-8   (ew-keynumber 'E6))
		(list 'SLAP-ROLL-9   (ew-keynumber 'F6))
		(list 'SHORT-ROLL-1  (ew-keynumber 'G6))
		(list 'SHORT-ROLL-2  (ew-keynumber 'A6))
		(list 'SHORT-ROLL-3  (ew-keynumber 'B6))
		(list 'SHORT-ROLL-4  (ew-keynumber 'C7)))))
   (setf (gethash '12-inch-tambourine remarks-table) "SD3 Small Drums  Remo 12in Italian Tambourine")
   (setf (gethash 'stick-tambourine keymap-table)
	 (circular-list-keynumber-map (list (ew-keynumber 'c1)
					    (ew-keynumber 'd1)
					    (ew-keynumber 'e1))))
   (setf (gethash 'stick-tambourine remarks-table) "SD3 Small Drums Tambourine with Stick")


   (setf (gethash 'pandero keymap-table)
	 (symbolic-keynumber-map
	  (list (list 'THUMB-OPEN  (ew-keynumber 'C1)) 
		(list 'THUMB-BEND  (ew-keynumber 'D1)) 
		(list 'FLAM        (ew-keynumber 'E1)) 
		(list 'FLAM-BEND   (ew-keynumber 'F1)) 
		(list 'THUMB       (ew-keynumber 'G1)) 
		(list 'SLAP-CENTER (ew-keynumber 'A1)) 
		(list 'PALM-CENTER (ew-keynumber 'B1)) 
		(list 'BACK-AND-FORTH (ew-keynumber 'C2)) 
		(list 'FINGER-1       (ew-keynumber 'D2)) 
		(list 'FINGER-2       (ew-keynumber 'E2)) 
		(list 'FINGER-EDGE    (ew-keynumber 'F2)) 
		(list 'JUNGLE-DOWN    (ew-keynumber 'G2)) 
		(list 'JUNGLE-UP      (ew-keynumber 'A2)) 
		(list 'PALM-ROLL      (ew-keynumber 'B2)) 
		(list 'JINGLE-DOWN-1  (ew-keynumber 'C3)) 
		(list 'JINGLE-DOWN-2  (ew-keynumber 'D3)) 
		(list 'JINGLE-UP-1    (ew-keynumber 'E3)) 
		(list 'JINGLE-UP-2    (ew-keynumber 'F3)) 
		(list 'FINGER-ROLL-1  (ew-keynumber 'G3)) 
		(list 'FINGER-ROLL-2  (ew-keynumber 'A3)) 
		(list 'FINGER-ROLL-3  (ew-keynumber 'B3)) 
		(list 'FINGER-ROLL-4  (ew-keynumber 'C4)))))
   (setf (gethash 'pandero remarks-table) "SD3 Small Drum Remo 10in Pandaro Skindeep Ultratech")
	 
   (sd3-instrument frame-drum ew-sd3-bigdrums keymap-table remarks-table)
   (sd3-query ?frame-drum 'frame-drum remarks-table))
