;;;; CYCO plugins sj sd3 bigdrums beast.lisp
;;;;
;;;; ew-sd3-bigdrums
;;;;  |
;;;;  +-- the-beast
;;;;        variations HITS ROLLS
;;;;

(param the-beast nil)

(let ((keymap-table (make-hash-table))
      (remarks-table (make-hash-table)))
  (setf (gethash 'hits keymap-table)
	(symbolic-keynumber-map
	 (list (list 'RIGHT-C-LH     (ew-keynumber 'C1) )
	       (list 'RIGHT-C-RH     (ew-keynumber 'D1) )
	       (list 'RIGHT-E-RH     (ew-keynumber 'E1) )
	       (list 'RIGHT-E-FLAM   (ew-keynumber 'F1) )
	       (list 'RIGHT-E-MUTE   (ew-keynumber 'G1) )
	       (list 'RIGHT-RIM-LH   (ew-keynumber 'A1) )
	       (list 'RIGHT-RIM-RH   (ew-keynumber 'B1) )
	       (list 'RIGHT-RIM-FLAM (ew-keynumber 'C2) )
	       (list 'RIGHT-ROLL-1   (ew-keynumber 'D2) )
	       (list 'RIGHT-ROLL-2   (ew-keynumber 'E2) )
	       (list 'RIGHT-ROLL-3   (ew-keynumber 'F2) )
	       (list 'RIGHT-ROLL-4   (ew-keynumber 'G2) )
	       (list 'HOME-LH        (ew-keynumber 'C3) )
	       (list 'HOME-RH        (ew-keynumber 'D3) )
	       (list 'HOME-OFFCENTER (ew-keynumber 'E3) )
	       (list 'CENTER-FLAM    (ew-keynumber 'F3) )
	       (list 'CENTER-MUTE    (ew-keynumber 'G3) )
	       (list 'LEFT-RIM-LH    (ew-keynumber 'A3) )
	       (list 'LEFT-RIM-RH    (ew-keynumber 'B3) )
	       (list 'LEFT-RIM-FLAM  (ew-keynumber 'C4) )
	       (list 'LEFT-C-ROLL-1  (ew-keynumber 'D4) )
	       (list 'LEFT-C-ROLL-2  (ew-keynumber 'E4) )
	       (list 'LEFT-C-ROLL-3  (ew-keynumber 'F4) )
	       (list 'LEFT-C-ROLL-4  (ew-keynumber 'G4) )
	       (list 'LEFT-E-LH      (ew-keynumber 'C5) )
	       (list 'LEFT-E-RH      (ew-keynumber 'D5) )
	       (list 'LEFT-E-CENTER  (ew-keynumber 'E5) )
	       (list 'LEFT-E-FLAM    (ew-keynumber 'F5) )
	       (list 'LEFT-E-MUTE    (ew-keynumber 'G5) )
	       (list 'SMALL-LH       (ew-keynumber 'A5) )
	       (list 'SMALL-RH       (ew-keynumber 'B5) )
	       (list 'SMALL-RIM-FLAM (ew-keynumber 'C6) )
	       (list 'LEFT-ROLL-1    (ew-keynumber 'D6) )
	       (list 'LEFT-ROLL-2    (ew-keynumber 'E6) )
	       (list 'LEFT-ROLL-3    (ew-keynumber 'F6) )
	       (list 'LEFT-ROLL-4    (ew-keynumber 'G6) ))))
  (setf (gethash 'hits remarks-table)
	"SD3 Big Drums  Dead The Beast Hits N Rolls")
  (setf (gethash 'rolls keymap-table)
	(symbolic-keynumber-map
	 (list (list 'LEFT-01   (ew-keynumber 'C1) )
	       (list 'LEFT-02   (ew-keynumber 'D1) )
	       (list 'LEFT-03   (ew-keynumber 'E1) )
	       (list 'LEFT-04   (ew-keynumber 'F1) )
	       (list 'LEFT-05   (ew-keynumber 'G1) )
	       (list 'LEFT-06   (ew-keynumber 'A1) )
	       (list 'LEFT-07   (ew-keynumber 'B1) )
	       (list 'LEFT-08   (ew-keynumber 'C2) )
	       (list 'LEFT-09   (ew-keynumber 'D2) )
	       (list 'LEFT-10   (ew-keynumber 'E2) )
	       (list 'LEFT-11   (ew-keynumber 'F2) )
	       (list 'CENTER-01 (ew-keynumber 'G2) )
	       (list 'CENTER-02 (ew-keynumber 'A2) )
	       (list 'CENTER-03 (ew-keynumber 'B2) )
	       (list 'CENTER-04 (ew-keynumber 'C3) )
	       (list 'CENTER-05 (ew-keynumber 'D3) )
	       (list 'CENTER-06 (ew-keynumber 'E3) )
	       (list 'CENTER-07 (ew-keynumber 'F3) )
	       (list 'CENTER-08 (ew-keynumber 'G3) )
	       (list 'CENTER-09 (ew-keynumber 'A3) )
	       (list 'CENTER-10 (ew-keynumber 'B3) )
	       (list 'CENTER-11 (ew-keynumber 'C4) )
	       (list 'CENTER-12 (ew-keynumber 'D4) )
	       (list 'RIGHT-01  (ew-keynumber 'E4) )
	       (list 'RIGHT-02  (ew-keynumber 'F4) )
	       (list 'RIGHT-03  (ew-keynumber 'G4) )
	       (list 'RIGHT-04  (ew-keynumber 'A4) )
	       (list 'RIGHT-05  (ew-keynumber 'B4) )
	       (list 'RIGHT-06  (ew-keynumber 'C5) )
	       (list 'RIGHT-07  (ew-keynumber 'D5) )
	       (list 'RIGHT-08  (ew-keynumber 'E5) )
	       (list 'RIGHT-09  (ew-keynumber 'F5) )
	       (list 'RIGHT-10  (ew-keynumber 'G5) )
	       (list 'RIGHT-11  (ew-keynumber 'A5) )
	       (list 'RIGHT-12  (ew-keynumber 'B5) ))))
  (setf (gethash 'rolls remarks-table)
	"SD3 Big Drums  Dead The Beast FX Rolls")

  (sd3-instrument the-beast ew-sd3-bigdrums keymap-table remarks-table)
  (sd3-query ?the-beast the-beast remarks-table) )
