;;;; CYCO plugins sj eastwest sd3 taiko negado.lisp
;;;;

(param negado nil)

(let ((keymap-table (make-hash-table))
      (remark-table (make-hash-table)))

  (setf
   (gethash '32 keymap-table)(symbolic-keynumber-map
			     (list
			      (list 'CENTER-LH   (ew-keynumber 'C1))
			      (list 'CENTER-RH   (ew-keynumber 'D1))
			      (list 'CENTER-FLAM (ew-keynumber 'E1))
			      (list 'SHORT-ROLL  (ew-keynumber 'F1))
			      (list 'RIM-LH      (ew-keynumber 'G1))
			      (list 'RIM-RH      (ew-keynumber 'A1))
			      (list 'RIM-FLAM    (ew-keynumber 'B1))
			      (list 'RIM-FLAM-DOUBLE (ew-keynumber 'C2))
			      (list 'RIM-ROLL-SHORT  (ew-keynumber 'D2))
			      (list 'ROLL-1 (ew-keynumber 'E2) "Crescendo roll")
			      (list 'ROLL-2 (ew-keynumber 'F2) "Crescendo roll")
			      (list 'ROLL-3 (ew-keynumber 'G2) "Crescendo roll")
			      (list 'ROLL-4 (ew-keynumber 'A2) "Crescendo roll")
			      (list 'ROLL-5 (ew-keynumber 'B2) "Crescendo rim roll")
			      (list 'ROLL-6 (ew-keynumber 'C3) "Crescendo rim roll")
			      (list 'ROLL-7 (ew-keynumber 'D3) "Crescendo tim roll")))

   (gethash '36-A keymap-table)(symbolic-keynumber-map
			       (list
				(list 'ENSEMBLE-HIT  (ew-keynumber 'C1)) 
				(list 'ENSEMBLE-FLAM (ew-keynumber 'D1)) 
				(list 'HIT           (ew-keynumber 'E1)) 
				(list 'BUZZ          (ew-keynumber 'F1)) 
				(list 'ENSEMBLE-RIM  (ew-keynumber 'G1)) 
				(list 'RIM           (ew-keynumber 'A1)) 
				(list 'ROLL-01 (ew-keynumber 'B1) "Long pp") 
				(list 'ROLL-02 (ew-keynumber 'C2) "Long p") 
				(list 'ROLL-03 (ew-keynumber 'D2) "Long mp")
				(list 'ROLL-04 (ew-keynumber 'E2) "Long F")
				(list 'ROLL-05 (ew-keynumber 'F2) "Long FF")
				(list 'ROLL-06 (ew-keynumber 'G2) "Short Crescendo")
				(list 'ROLL-07 (ew-keynumber 'A2) "Short Crescendo")
				(list 'ROLL-08 (ew-keynumber 'B2) "Short Crescendo")
				(list 'ROLL-09 (ew-keynumber 'C3) "Short Crescendo")
				(list 'ROLL-10 (ew-keynumber 'D3) "Short Crescendo")
				(list 'SCRAPE-01 (ew-keynumber 'E3)) 
				(list 'SCRAPE-02 (ew-keynumber 'F3)) 
				(list 'SCRAPE-03 (ew-keynumber 'G3)) 
				(list 'SCRAPE-04 (ew-keynumber 'A3)) 
				(list 'SCRAPE-05 (ew-keynumber 'B3)) 
				(list 'SCRAPE-06 (ew-keynumber 'C4)) 
				(list 'SCRAPE-07 (ew-keynumber 'D4)) 
				(list 'SCRAPE-08 (ew-keynumber 'E4)) 
				(list 'SCRAPE-09 (ew-keynumber 'F4)) 
				(list 'SCRAPE-10 (ew-keynumber 'G4)) 
				(list 'SCRAPE-11 (ew-keynumber 'A4))))

   (gethash '36-b keymap-table)(symbolic-keynumber-map
			       (list
				(list 'ENSEMBLE-HIT  (ew-keynumber 'C1)) 
				(list 'ENSEMBLE-FLAM (ew-keynumber 'D1)) 
				(list 'HIT           (ew-keynumber 'E1)) 
				(list 'BUZZ          (ew-keynumber 'F1)) 
				(list 'ENSEMBLE-RIM  (ew-keynumber 'G1)) 
				(list 'RIM           (ew-keynumber 'A1)) 
				(list 'ROLL-1 (ew-keynumber 'B1)) 
				(list 'ROLL-2 (ew-keynumber 'C2)) 
				(list 'ROLL-3 (ew-keynumber 'D2)) 
				(list 'ROLL-4 (ew-keynumber 'E2)) 
				(list 'ROLL-5 (ew-keynumber 'F2)) 
				(list 'ROLL-6 (ew-keynumber 'G2)) 
				(list 'ROLL-7 (ew-keynumber 'A2)) 
				(list 'SCRAPE-1 (ew-keynumber 'B2)) 
				(list 'SCRAPE-2 (ew-keynumber 'C3)) 
				(list 'SCRAPE-3 (ew-keynumber 'D3)) 
				(list 'SCRAPE-4 (ew-keynumber 'E3)) 
				(list 'SCRAPE-5 (ew-keynumber 'F3)) 
				(list 'SCRAPE-6 (ew-keynumber 'G3)) 
				(list 'SCRAPE-7 (ew-keynumber 'A3)) 
				(list 'SCRAPE-8  (ew-keynumber 'B3))))

   (gethash '46 keymap-table)(symbolic-keynumber-map
			     (list
			      (LIST 'MALLET       (ew-keynumber 'C1)) 
			      (LIST 'CENTER       (ew-keynumber 'D1)) 
			      (LIST 'EDGE-FLAM    (ew-keynumber 'E1)) 
			      (LIST 'CENTER-FLAM  (ew-keynumber 'F1)) 
			      (LIST 'EDGE         (ew-keynumber 'G1)) 
			      (LIST 'ENSEMBLE-HIT (ew-keynumber 'A1)) 
			      (LIST 'BAMBOO-HIT   (ew-keynumber 'B1)) 
			      (LIST 'BUZZ         (ew-keynumber 'C2)) 
			      (LIST 'ENSEMBLE-RIM (ew-keynumber 'D2)) 
			      (LIST 'STICK-RIM    (ew-keynumber 'E2)) 
			      (LIST 'ROLL-01 (ew-keynumber 'F2) "Long mallet roll")
			      (LIST 'ROLL-02 (ew-keynumber 'G2) "Long stick roll")
			      (LIST 'ROLL-03 (ew-keynumber 'A2) "Mallet roll cresendo") 
			      (LIST 'ROLL-04 (ew-keynumber 'B2) "Mallet roll cresendo") 
			      (LIST 'ROLL-05 (ew-keynumber 'C3) "Mallet roll cresendo") 
			      (LIST 'ROLL-06 (ew-keynumber 'D3) "Mallet roll cresendo") 
			      (LIST 'ROLL-07 (ew-keynumber 'E3) "Stick roll cresendo") 
			      (LIST 'ROLL-08 (ew-keynumber 'F3) "Stick roll cresendo") 
			      (LIST 'ROLL-09 (ew-keynumber 'G3) "Stick roll cresendo") 
			      (LIST 'ROLL-10 (ew-keynumber 'A3) "Stick roll cresendo") 
			      (LIST 'ROLL-11 (ew-keynumber 'B3) "Stick roll cresendo") 
			      (LIST 'RIM-PERF  (ew-keynumber 'C4)) 
			      (LIST 'SCRAPE-01 (ew-keynumber 'C4)) 
			      (LIST 'SCRAPE-02 (ew-keynumber 'D4)) 
			      (LIST 'SCRAPE-03 (ew-keynumber 'E4)) 
			      (LIST 'SCRAPE-04 (ew-keynumber 'F4)) 
			      (LIST 'SCRAPE-05 (ew-keynumber 'G4)) 
			      (LIST 'SCRAPE-06 (ew-keynumber 'A4)) 
			      (LIST 'SCRAPE-07 (ew-keynumber 'B4)) 
			      (LIST 'SCRAPE-08 (ew-keynumber 'C5)) 
			      (LIST 'SCRAPE-09 (ew-keynumber 'D5)) 
			      (LIST 'SCRAPE-10 (ew-keynumber 'E5)) 
			      (LIST 'SCRAPE-11 (ew-keynumber 'F5)) 
			      (LIST 'SCRAPE-12 (ew-keynumber 'G5)) 
			      (LIST 'SCRAPE-13 (ew-keynumber 'A5)) 
			      (LIST 'SCRAPE-14 (ew-keynumber 'B5)) 
			      (LIST 'SCRAPE-15 (ew-keynumber 'C6)) 
			      (LIST 'SCRAPE-16 (ew-keynumber 'D6)))))
   (setf (gethash '32 remark-table) "SD3 Taiko Remo 32in Negado Odaiko"
	 (gethash '36-A remark-table) "SD3 Taiko 36in Negado Head A"
	 (gethash '36-B remark-table) "SD3 Taiko 36in Negado Head B"
	 (gethash '46 remark-table) "SD3 Taiko 46in 800lb Negado Daiko")
   (sd3-instrument negado ew-sd3-taiko keymap-table remark-table)
   (sd3-query ?negado 'negado remark-table)) 
   
